# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 10:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161207_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='/blog/static/imgs'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 8, 10, 18, 47, 923903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 8, 10, 18, 47, 922049, tzinfo=utc)),
        ),
    ]
