# Generated by Django 2.0 on 2017-12-11 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171205_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 21, 56, 1, 767708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 11, 21, 56, 1, 767050, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('travel', 'travel'), ('food', 'food'), ('sport', 'sport')], default='Travel', max_length=50),
        ),
    ]
