# Generated by Django 2.0 on 2017-12-12 00:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171211_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 0, 20, 4, 790347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 0, 20, 4, 789620, tzinfo=utc)),
        ),
    ]
